---
apiVersion: s3.stackable.tech/v1alpha1
kind: S3Bucket
metadata:
  name: my-bucket-resource
spec:
  bucketName: my-example-bucket
  connection:
    inline:
      host: s3-eu-central-1.ionoscloud.com
      port: 443
      tls:
        verification:
          server:
            caCert:
              webPki: {}
      credentials:
        secretClass: s3-credentials-class
