---
apiVersion: edc.stackable.tech/v1alpha1
kind: EDCCluster
metadata:
  name: provider
spec:
  image:
    custom: docker.stackable.tech/sandbox/edc:77c6e17-stackable0.0.0-dev
    productVersion: 0.0.1
  clusterConfig:
    listenerClass: external-unstable
    certSecret: connector-cert
    ionos:
      tokenSecret: ionos-token
      s3: 
        reference: source-bucket
  connectors:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: edc.stackable.tech/v1alpha1
kind: EDCCluster
metadata:
  name: consumer
spec:
  image:
    custom: docker.stackable.tech/sandbox/edc:77c6e17-stackable0.0.0-dev
    productVersion: 0.0.1
  clusterConfig:
    listenerClass: external-unstable
    certSecret: connector-cert
    ionos:
      tokenSecret: ionos-token
      s3:
        reference: destination-bucket
  connectors:
    roleGroups:
      default:
        replicas: 1
