---
apiVersion: edc.stackable.tech/v1alpha1
kind: EDCCluster
metadata:
  name: edc-provider
spec:
  image:
    custom: edc-ionos:v0
    productVersion: 0.1.0
  clusterConfig:
    listenerClass: external-unstable
    certSecret: consumer-cert
  connectors:
    roleGroups:
      default:
        replicas: 1