---
apiVersion: edc.stackable.tech/v1alpha1
kind: EDCCluster
metadata:
  name: edc-provider
spec:
  image:
    custom: edc-ionos:v0
    productVersion: 0.1.0
  clusterConfig:
    listenerClass: external-unstable
    certSecret: consumer-cert
    s3:
      inline:
        bucketName: my-bucket
        connection:
          inline:
            host: ionos.com # TODO
            port: 443       # TODO
            credentials:
              secretClass: s3-credentials-class
  connectors:
    roleGroups:
      default:
        replicas: 1