---
apiVersion: edc.stackable.tech/v1alpha1
kind: EDCCluster
metadata:
  name: connector
spec:
  image:
    custom: docker.stackable.tech/sandbox/edc:0.0.1-SNAPSHOT-stackable0.0.0-dev
    productVersion: 0.0.1
  clusterConfig:
    listenerClass: external-unstable
    certSecret: connector-cert
    vectorAggregatorConfigMapName: vector-aggregator-discovery
  connectors:
    roleGroups:
      default:
        replicas: 1