---
apiVersion: edc.stackable.tech/v1alpha1
kind: EDCCluster
metadata:
  name: connector
spec:
  image:
    custom: docker.stackable.tech/stackable-experimental/edc:0.1.2-ionos-technology-preview-stackable0.0.0-dev
    productVersion: 0.1.2
  clusterConfig:
    listenerClass: external-unstable
    certSecret: connector-cert
    vectorAggregatorConfigMapName: vector-aggregator-discovery
    ionos:
      tokenSecret: ionos-token
      s3:
        inline:
          bucketName: my-bucket
          connection:
            inline:
              host: ionos.com # TODO
              port: 443       # TODO
              credentials:
                secretClass: s3-credentials-class
  connectors:
    config:
      logging:
        enableVectorAgent: true
        containers:
          connector:
            console:
              level: INFO
            file:
              level: INFO
            loggers:
              ROOT:
                level: INFO
          vector:
            console:
              level: INFO
            file:
              level: INFO
            loggers:
              ROOT:
                level: INFO
    roleGroups:
      default:
        replicas: 1
