---
apiVersion: edc.stackable.tech/v1alpha1
kind: EDCCluster
metadata:
  name: provider
spec:
  image:
    custom: docker.stackable.tech/sandbox/edc:77c6e17-stackable0.0.0-dev
    productVersion: 0.0.1
  clusterConfig:
    listenerClass: external-unstable
    certSecret: connector-cert
    s3:
      inline:
        bucketName: source-bucket
        connection:
          inline:
            host: ionos.com # TODO
            port: 443       # TODO
            credentials:
              secretClass: s3-credentials-class
  connectors:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: edc.stackable.tech/v1alpha1
kind: EDCCluster
metadata:
  name: consumer
spec:
  image:
    custom: docker.stackable.tech/sandbox/edc:77c6e17-stackable0.0.0-dev
    productVersion: 0.0.1
  clusterConfig:
    listenerClass: external-unstable
    certSecret: connector-cert
    s3:
      inline:
        bucketName: destination-bucket
        connection:
          inline:
            host: ionos.com # TODO
            port: 443       # TODO
            credentials:
              secretClass: s3-credentials-class
  connectors:
    roleGroups:
      default:
        replicas: 1
        configOverrides:
          config.properties:
            edc.ionos.token: YOUR_TOKEN_HERE
